FROM golang:1.20.9-bullseye AS base

ENV GOVCS="false"
ENV APP_HOME /app
WORKDIR $APP_HOME

FROM base AS dev

RUN go install github.com/cosmtrek/air@v1.49.0

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY ./ $APP_HOME

RUN go build -ldflags "-s -w" -buildvcs=false -o $APP_HOME/main

CMD air

FROM dev AS test

# Use for tests

# Smaller build for prod
FROM debian:bullseye-slim AS release

ENV APP_HOME /app
WORKDIR $APP_HOME

COPY --chown=0:0 --from=dev $APP_HOME/main $APP_HOME/main

CMD $APP_HOME/main start-server
